apiBaseUrl=http://localhost:4111
#apiBaseUrl=http://192.168.0.16:4111
apiVersion=/api/v1/
api.version=with_database

admin.username=admin
admin.password=admin

uiRemote=http://localhost:4444/wd/hub
uiBaseUrl=http://192.168.0.16:80
browser=chrome
browserVersion=latest
browserSize=1920x1080


# Database configuration
db.url=jdbc:postgresql://localhost:5433/nbank
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver
db.table.customers=customers

# Fraud service configuration (for testing with WireMock)
fraud.service.url=http://localhost:8080