# Format: RequestClass->ResponseClass:ResponseClass:field1=field1Response,field2=field2Response

CreateUserRequest->CreateUserResponse:CreateUserResponse:username=username,role=role
CreateDepositRequest->CreateDepositResponse:CreateDepositResponse:id=id,balance=balance
InfoPutUserResponse->CreateUserRequest:CreateUserRequest:customer.username=username,customer.role=role
InfoGetUserResponse->CreateUserRequest:CreateUserRequest:username=username
InfoGetUserResponse->CreateUserResponse:CreateUserResponse:id=id,password=password

