services:
  backend:
    image: nobugsme/nbank:with_database
    ports:
      - "4111:4111"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/nbank
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nbank-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=nbank
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - nbank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nbank"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - nbank-network

networks:
  nbank-network:

volumes:
  postgres_data: